require 'rubygems'
require File.dirname(__FILE__) + '/rfetion/buddy_list'
require File.dirname(__FILE__) + '/rfetion/contact'
require File.dirname(__FILE__) + '/rfetion/message'
require File.dirname(__FILE__) + '/rfetion/sipc_message'
require File.dirname(__FILE__) + '/rfetion/fetion'
